use_frameworks!

target 'iStatusView_Example' do
  pod 'iStatusView', :path => '../'
  pod 'SVProgressHUD'
  pod 'SnapKit'

  target 'iStatusView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0'
    pod 'Nimble', '~> 8.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 8.2'
  end
end
