platform :ios, '10.0'
use_frameworks!

target 'iStatusView_Example' do
  pod 'iStatusView', :path => '../'
  pod 'SVProgressHUD'
  pod 'SnapKit'

  target 'iStatusView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 8.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 7.0'
  end
end
